# Generated by Django 4.1 on 2022-11-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="fileattach", name="article",),
        migrations.DeleteModel(name="Article",),
        migrations.DeleteModel(name="FileAttach",),
        migrations.DeleteModel(name="User",),
    ]
